// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BhwwoBC1yBfDaWh_Lu3muKa1xPqMCHM',
    appId: '1:540819165123:android:4226471f7b51833b85b776',
    messagingSenderId: '540819165123',
    projectId: 'brain-saver-7dce2',
    storageBucket: 'brain-saver-7dce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvx1XhzIDgsCeX4EZHck3DqY8-ZykZ0xg',
    appId: '1:540819165123:ios:0d42067082a984a585b776',
    messagingSenderId: '540819165123',
    projectId: 'brain-saver-7dce2',
    storageBucket: 'brain-saver-7dce2.appspot.com',
    iosClientId: '540819165123-bc3hvggnsrd7h02mqjcmsidmdvb5s61i.apps.googleusercontent.com',
    iosBundleId: 'com.rlebranchu.brainsaver',
  );
}
